name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Find Build Folder and Disable Jekyll
        id: build_dir
        run: |
          if [ -d "./dist" ]; then
            touch ./dist/.nojekyll
            echo "path=./dist" >> $GITHUB_OUTPUT
          elif [ -d "./.output/public" ]; then
            touch ./.output/public/.nojekyll
            echo "path=./.output/public" >> $GITHUB_OUTPUT
          elif [ -d "./build" ]; then
            touch ./build/.nojekyll
            echo "path=./build" >> $GITHUB_OUTPUT
          else
            echo "Error: Could not find output folder. Listing files:"
            ls -la
            exit 1
          fi
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ steps.build_dir.outputs.path }}

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
